// <auto-generated />
using System;
using FourAsset.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FourAsset.Infra.Data.Migrations
{
    [DbContext(typeof(FourAssetContext))]
    [Migration("20191218125100_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FourAsset.Domain.Models.Tarefa", b =>
                {
                    b.Property<int>("TarefaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataDeConclusao");

                    b.Property<DateTime>("DataDeCriacao");

                    b.Property<DateTime>("DataDeEdicao");

                    b.Property<DateTime>("DataDeRemocao");

                    b.Property<string>("Descricao");

                    b.Property<bool>("Status");

                    b.Property<string>("Titulo");

                    b.HasKey("TarefaId");

                    b.ToTable("Tarefas");

                    b.HasData(
                        new
                        {
                            TarefaId = 1,
                            DataDeConclusao = new DateTime(2019, 12, 18, 10, 6, 0, 380, DateTimeKind.Local).AddTicks(7092),
                            DataDeCriacao = new DateTime(2019, 12, 18, 9, 51, 0, 377, DateTimeKind.Local).AddTicks(6992),
                            DataDeEdicao = new DateTime(2019, 12, 18, 10, 11, 0, 380, DateTimeKind.Local).AddTicks(5341),
                            DataDeRemocao = new DateTime(2019, 12, 18, 10, 16, 0, 380, DateTimeKind.Local).AddTicks(8039),
                            Descricao = "Tarefa de teste 1",
                            Status = false,
                            Titulo = "Tarefa 1"
                        },
                        new
                        {
                            TarefaId = 2,
                            DataDeConclusao = new DateTime(2019, 12, 18, 10, 11, 0, 380, DateTimeKind.Local).AddTicks(9080),
                            DataDeCriacao = new DateTime(2019, 12, 18, 9, 51, 0, 380, DateTimeKind.Local).AddTicks(9048),
                            DataDeEdicao = new DateTime(2019, 12, 18, 10, 16, 0, 380, DateTimeKind.Local).AddTicks(9071),
                            DataDeRemocao = new DateTime(2019, 12, 18, 10, 21, 0, 380, DateTimeKind.Local).AddTicks(9089),
                            Descricao = "Tarefa de teste 2",
                            Status = false,
                            Titulo = "Tarefa 2"
                        },
                        new
                        {
                            TarefaId = 3,
                            DataDeConclusao = new DateTime(2019, 12, 18, 10, 16, 0, 380, DateTimeKind.Local).AddTicks(9107),
                            DataDeCriacao = new DateTime(2019, 12, 18, 9, 51, 0, 380, DateTimeKind.Local).AddTicks(9098),
                            DataDeEdicao = new DateTime(2019, 12, 18, 10, 21, 0, 380, DateTimeKind.Local).AddTicks(9103),
                            DataDeRemocao = new DateTime(2019, 12, 18, 10, 26, 0, 380, DateTimeKind.Local).AddTicks(9111),
                            Descricao = "Tarefa de teste 3",
                            Status = false,
                            Titulo = "Tarefa 2"
                        },
                        new
                        {
                            TarefaId = 4,
                            DataDeConclusao = new DateTime(2019, 12, 18, 10, 21, 0, 380, DateTimeKind.Local).AddTicks(9125),
                            DataDeCriacao = new DateTime(2019, 12, 18, 9, 51, 0, 380, DateTimeKind.Local).AddTicks(9117),
                            DataDeEdicao = new DateTime(2019, 12, 18, 10, 26, 0, 380, DateTimeKind.Local).AddTicks(9120),
                            DataDeRemocao = new DateTime(2019, 12, 18, 10, 31, 0, 380, DateTimeKind.Local).AddTicks(9129),
                            Descricao = "Tarefa de teste 4",
                            Status = false,
                            Titulo = "Tarefa 4"
                        },
                        new
                        {
                            TarefaId = 5,
                            DataDeConclusao = new DateTime(2019, 12, 18, 10, 26, 0, 380, DateTimeKind.Local).AddTicks(9142),
                            DataDeCriacao = new DateTime(2019, 12, 18, 9, 51, 0, 380, DateTimeKind.Local).AddTicks(9134),
                            DataDeEdicao = new DateTime(2019, 12, 18, 10, 31, 0, 380, DateTimeKind.Local).AddTicks(9138),
                            DataDeRemocao = new DateTime(2019, 12, 18, 10, 36, 0, 380, DateTimeKind.Local).AddTicks(9146),
                            Descricao = "Tarefa de teste 5",
                            Status = false,
                            Titulo = "Tarefa 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
