// <auto-generated />
using System;
using FourAsset.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FourAsset.Infra.Data.Migrations
{
    [DbContext(typeof(FourAssetContext))]
    [Migration("20191219041824_tarefaConfiguration")]
    partial class tarefaConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FourAsset.Domain.Models.Tarefa", b =>
                {
                    b.Property<int>("TarefaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataDeConclusao");

                    b.Property<DateTime>("DataDeCriacao");

                    b.Property<DateTime>("DataDeEdicao");

                    b.Property<DateTime>("DataDeRemocao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(5000);

                    b.Property<bool>("Status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("TarefaId");

                    b.ToTable("Tarefas");

                    b.HasData(
                        new
                        {
                            TarefaId = 1,
                            DataDeConclusao = new DateTime(2019, 12, 19, 1, 33, 23, 678, DateTimeKind.Local).AddTicks(2681),
                            DataDeCriacao = new DateTime(2019, 12, 19, 1, 18, 23, 678, DateTimeKind.Local).AddTicks(1363),
                            DataDeEdicao = new DateTime(2019, 12, 19, 1, 38, 23, 678, DateTimeKind.Local).AddTicks(1412),
                            DataDeRemocao = new DateTime(2019, 12, 19, 1, 43, 23, 678, DateTimeKind.Local).AddTicks(3989),
                            Descricao = "Tarefa de teste 1",
                            Status = false,
                            Titulo = "Tarefa 1"
                        },
                        new
                        {
                            TarefaId = 2,
                            DataDeConclusao = new DateTime(2019, 12, 19, 1, 38, 23, 678, DateTimeKind.Local).AddTicks(5504),
                            DataDeCriacao = new DateTime(2019, 12, 19, 1, 18, 23, 678, DateTimeKind.Local).AddTicks(5478),
                            DataDeEdicao = new DateTime(2019, 12, 19, 1, 43, 23, 678, DateTimeKind.Local).AddTicks(5486),
                            DataDeRemocao = new DateTime(2019, 12, 19, 1, 48, 23, 678, DateTimeKind.Local).AddTicks(5520),
                            Descricao = "Tarefa de teste 2",
                            Status = false,
                            Titulo = "Tarefa 2"
                        },
                        new
                        {
                            TarefaId = 3,
                            DataDeConclusao = new DateTime(2019, 12, 19, 1, 43, 23, 678, DateTimeKind.Local).AddTicks(5559),
                            DataDeCriacao = new DateTime(2019, 12, 19, 1, 18, 23, 678, DateTimeKind.Local).AddTicks(5544),
                            DataDeEdicao = new DateTime(2019, 12, 19, 1, 48, 23, 678, DateTimeKind.Local).AddTicks(5552),
                            DataDeRemocao = new DateTime(2019, 12, 19, 1, 53, 23, 678, DateTimeKind.Local).AddTicks(5565),
                            Descricao = "Tarefa de teste 3",
                            Status = false,
                            Titulo = "Tarefa 2"
                        },
                        new
                        {
                            TarefaId = 4,
                            DataDeConclusao = new DateTime(2019, 12, 19, 1, 48, 23, 678, DateTimeKind.Local).AddTicks(5595),
                            DataDeCriacao = new DateTime(2019, 12, 19, 1, 18, 23, 678, DateTimeKind.Local).AddTicks(5582),
                            DataDeEdicao = new DateTime(2019, 12, 19, 1, 53, 23, 678, DateTimeKind.Local).AddTicks(5588),
                            DataDeRemocao = new DateTime(2019, 12, 19, 1, 58, 23, 678, DateTimeKind.Local).AddTicks(5603),
                            Descricao = "Tarefa de teste 4",
                            Status = false,
                            Titulo = "Tarefa 4"
                        },
                        new
                        {
                            TarefaId = 5,
                            DataDeConclusao = new DateTime(2019, 12, 19, 1, 53, 23, 678, DateTimeKind.Local).AddTicks(5631),
                            DataDeCriacao = new DateTime(2019, 12, 19, 1, 18, 23, 678, DateTimeKind.Local).AddTicks(5618),
                            DataDeEdicao = new DateTime(2019, 12, 19, 1, 58, 23, 678, DateTimeKind.Local).AddTicks(5624),
                            DataDeRemocao = new DateTime(2019, 12, 19, 2, 3, 23, 678, DateTimeKind.Local).AddTicks(5638),
                            Descricao = "Tarefa de teste 5",
                            Status = false,
                            Titulo = "Tarefa 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
